// Copyright © Team DDS 2025. Project DDS™ is a trademark of Team DDS. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace DDSGameplayTags
{
	/** Input Tags */
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LockOn)

	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UI_MainMenu_ToggleUI)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UI_Crafting_ToggleUI)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UI_Crafting_RemoveItem)
	
	
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipWeapon01)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipWeapon01)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipWeapon02)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipWeapon02)

	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack)

	/** Player Tags */
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Jump)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_LockOn)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Sword)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Sword)
	
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_LightAttack_Sword)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_HeavyAttack_Sword)
	
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword)
	
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Sword)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Sword)

	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy)

	/** Monster Tags */
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster_Weapon)

	/** Shared Tags */

	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit_Start);
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit_End);

	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);
	
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_LockedOn)
	
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_DamgeType_Physical)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_DamgeType_Fire)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_DamgeType_Magic)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_DamgeType_Holy)

	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_ResistType_Physical)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_ResistType_Fire)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_ResistType_Magic)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_ResistType_Holy)

	/** Item Tags */
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Dev)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Junk)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Quest)

	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Armor)
	
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Simple)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Crafted)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_WeaponPart_Blade)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_WeaponPart_Grip)
	DDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_WeaponPart_Pommel)



	
	
	
}
 